version: '3.6'
services:
  web:
    build: ./docker-nginx
    ports:
        - 80:80
    depends_on:
        - php
    volumes:
        - ./:/var/www/html
        - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php   
  php:
    build: ./docker-php
    depends_on:
        - postgres
    links:
        - postgres
    volumes:
        - ./:/var/www/html  

  postgres:
    image: postgres:13.3
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:

